# Generated by Django 4.2.8 on 2024-01-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='clothing_size',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
