# Generated by Django 4.2.8 on 2023-12-16 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='item',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='user',
        ),
        migrations.AddField(
            model_name='ratings',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='item_ratings', to='e_commerce.items'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratings',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
