# Generated by Django 4.2.8 on 2024-01-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0002_alter_items_clothing_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='shoe_size',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
