# Generated by Django 4.2.8 on 2023-12-17 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0003_remove_comments_item_remove_comments_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items_count',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
    ]
