# Generated by Django 4.2.8 on 2023-12-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0005_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
