# Generated by Django 4.2.8 on 2023-12-18 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0008_cartitem_orderitem_remove_cart_transactions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
