# Generated by Django 4.2.8 on 2023-12-19 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0009_remove_cart_items_remove_order_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_verificatoin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
