# Generated by Django 4.2.8 on 2023-12-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0010_verification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='item',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='user',
        ),
        migrations.AddField(
            model_name='items',
            name='category',
            field=models.ManyToManyField(to='e_commerce.categories'),
        ),
    ]
