# Generated by Django 4.2.8 on 2024-01-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0011_remove_categories_item_remove_categories_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.ManyToManyField(blank=True, to='e_commerce.categories'),
        ),
    ]
